//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cip.LabDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Cip_LabDemo_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cip_LabDemo_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cip.LabDemo.Resources.Cip.LabDemo.Strings", typeof(Cip_LabDemo_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Caption_Error {
            get {
                return ResourceManager.GetString("Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Error.
        /// </summary>
        internal static string Caption_IOError {
            get {
                return ResourceManager.GetString("Caption_IOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Caption_Warning {
            get {
                return ResourceManager.GetString("Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Image Processing.
        /// </summary>
        internal static string Cip_Name {
            get {
                return ResourceManager.GetString("Cip_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black and white image.
        /// </summary>
        internal static string Description_BlackAndWhiteImage {
            get {
                return ResourceManager.GetString("Description_BlackAndWhiteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color addition example.
        /// </summary>
        internal static string Description_ColorAdditionExample {
            get {
                return ResourceManager.GetString("Description_ColorAdditionExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction result.
        /// </summary>
        internal static string Description_CorrectionResult {
            get {
                return ResourceManager.GetString("Description_CorrectionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark image.
        /// </summary>
        internal static string Description_DarkImage {
            get {
                return ResourceManager.GetString("Description_DarkImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference between methods in RGB and HSI colorspaces.
        /// </summary>
        internal static string Description_DifferenceBetweenRgbHsi {
            get {
                return ResourceManager.GetString("Description_DifferenceBetweenRgbHsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example from DIP book.
        /// </summary>
        internal static string Description_ExampleCutFromDip {
            get {
                return ResourceManager.GetString("Description_ExampleCutFromDip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue component.
        /// </summary>
        internal static string Description_HueComponent {
            get {
                return ResourceManager.GetString("Description_HueComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image after bloom.
        /// </summary>
        internal static string Description_ImageAfterBloom {
            get {
                return ResourceManager.GetString("Description_ImageAfterBloom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image after smoothing with mask 5x5.
        /// </summary>
        internal static string Description_ImageAfterBlur5x5 {
            get {
                return ResourceManager.GetString("Description_ImageAfterBlur5x5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image after histogram equalization.
        /// </summary>
        internal static string Description_ImageAfterEqualization {
            get {
                return ResourceManager.GetString("Description_ImageAfterEqualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image after histogram normalization.
        /// </summary>
        internal static string Description_ImageAfterNormalization {
            get {
                return ResourceManager.GetString("Description_ImageAfterNormalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image after processing.
        /// </summary>
        internal static string Description_ImageAfterProcessing {
            get {
                return ResourceManager.GetString("Description_ImageAfterProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image after Sepia filter.
        /// </summary>
        internal static string Description_ImageAfterSepia {
            get {
                return ResourceManager.GetString("Description_ImageAfterSepia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image after sharpening.
        /// </summary>
        internal static string Description_ImageAfterSharpening {
            get {
                return ResourceManager.GetString("Description_ImageAfterSharpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image after thresholding.
        /// </summary>
        internal static string Description_ImageAfterThresholding {
            get {
                return ResourceManager.GetString("Description_ImageAfterThresholding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light image.
        /// </summary>
        internal static string Description_LightImage {
            get {
                return ResourceManager.GetString("Description_LightImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low contrast image.
        /// </summary>
        internal static string Description_LowContrastImage {
            get {
                return ResourceManager.GetString("Description_LowContrastImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masks.
        /// </summary>
        internal static string Description_Masks {
            get {
                return ResourceManager.GetString("Description_Masks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string Description_Original {
            get {
                return ResourceManager.GetString("Description_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under construction....
        /// </summary>
        internal static string Description_UnderConstruction {
            get {
                return ResourceManager.GetString("Description_UnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application can&apos;t LOAD.
        /// </summary>
        internal static string Message_LoadFilePart1 {
            get {
                return ResourceManager.GetString("Message_LoadFilePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file, that should be in the directory.
        /// </summary>
        internal static string Message_LoadFilePart2 {
            get {
                return ResourceManager.GetString("Message_LoadFilePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of application.
        /// </summary>
        internal static string Message_LoadFilePart3 {
            get {
                return ResourceManager.GetString("Message_LoadFilePart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will reload application and all data will be lost!.
        /// </summary>
        internal static string Message_ReloadApplication {
            get {
                return ResourceManager.GetString("Message_ReloadApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application can&apos;t SAVE.
        /// </summary>
        internal static string Message_SaveFilePart1 {
            get {
                return ResourceManager.GetString("Message_SaveFilePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file to this.
        /// </summary>
        internal static string Message_SaveFilePart2 {
            get {
                return ResourceManager.GetString("Message_SaveFilePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  directory!.
        /// </summary>
        internal static string Message_SaveFilePart3 {
            get {
                return ResourceManager.GetString("Message_SaveFilePart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This save function only for Editor tab modifyed image! Save image?.
        /// </summary>
        internal static string Message_SaveFunctionWarning {
            get {
                return ResourceManager.GetString("Message_SaveFunctionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal mode.
        /// </summary>
        internal static string Mode_Normal {
            get {
                return ResourceManager.GetString("Mode_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch mode.
        /// </summary>
        internal static string Mode_Stretch {
            get {
                return ResourceManager.GetString("Mode_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom mode.
        /// </summary>
        internal static string Mode_Zoom {
            get {
                return ResourceManager.GetString("Mode_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open picture.
        /// </summary>
        internal static string Open_Image {
            get {
                return ResourceManager.GetString("Open_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save picture.
        /// </summary>
        internal static string Save_Image {
            get {
                return ResourceManager.GetString("Save_Image", resourceCulture);
            }
        }
    }
}
